### ISSUE TITLE
Aireos is not supported with network_cli as we move to collections in 2.10 

### ISSUE THREAD

**Issue by t1hom7as** [ansible-collections/community.network#119]
##### SUMMARY
Note: I have been doing this on 2.9.11, but actively trying to migrate to collections ready for 2.10.

As we go to 2.10, the new aireos_config is now in the community.network collection, as per the documentation:  https://docs.ansible.com/ansible/latest/collections/community/network/aireos_config_module.html 

This leads us to: https://github.com/ansible-collections/community.network#supported-connections
Which states that only network_cli or httpapi can be used.

Inside of https://docs.ansible.com/ansible/latest/network/user_guide/platform_index.html there is not aireos, so I think this has been missed when migrating to this new collection and out of Ansible base.  

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.network
community.network.aireos_config

##### ANSIBLE VERSION

```paste below
2.9.11
```

##### CONFIGURATION

```ANSIBLE_SSH_RETRIES(/Users/user/scripts/testing/ansible.cfg) = 3
COLLECTIONS_PATHS(/Users/user/scripts/testing/ansible.cfg) = ['/Users/user/scripts/testing']
DEFAULT_NO_LOG(/Users/user/scripts/testing/ansible.cfg) = False
DEFAULT_STRATEGY(/Users/user/scripts/testing/ansible.cfg) = free
DISPLAY_SKIPPED_HOSTS(/Users/user/scripts/testing/ansible.cfg) = True
GALAXY_IGNORE_CERTS(/Users/user/scripts/testing/ansible.cfg) = True
HOST_KEY_CHECKING(/Users/user/scripts/testing/ansible.cfg) = False
PARAMIKO_HOST_KEY_AUTO_ADD(/Users/user/scripts/testing/ansible.cfg) = True
PARAMIKO_LOOK_FOR_KEYS(/Users/user/scripts/testing/ansible.cfg) = False
RETRY_FILES_ENABLED(/Users/user/scripts/testing/ansible.cfg) = False

```

##### OS / ENVIRONMENT

Ansible AWX 14.1 - Centos 8 
macOS 10.15.6 

##### STEPS TO REPRODUCE

site.yaml:
```- connection: "ansible.netcommon.network_cli"
  gather_facts: false
  hosts: "wlc"
  collections:
    - "community.network"
  tasks:
    - name: "Import Wireless LAN Controller tasks"
      import_tasks: "roles/wlc/tasks/main.yml"
```
main.yml:
```
- name: "TASK 5"
  block:
  - name: "TASK 5 -"
    community.network.aireos_config:
      lines:
        - "mgmtuser password localadmin {{ new_password }}"
        - "ap mgmtuser add username localadmin password {{ new_password }} secret {{ new_password }} all"
      save_when: "changed"
    vars:
      ansible_network_os: "aireos"  
```

##### EXPECTED RESULTS
The playbook to be executed correctly.

##### ACTUAL RESULTS
```
"msg": "invalid connection specified, expected connection=local, got ansible.netcommon.network_cli"
```
