### ISSUE TITLE
aruba_config unable to save configuration on Aruba 2930F

### ISSUE THREAD

**Issue by navvisit** [ansible-collections/community.network#145]
##### SUMMARY
When trying to write the configuration on Aruba 2930F, it fails with the following message:

```
ansible-playbook -i hosts examples.yml -k


SSH password:

PLAY [switch01] *********************************************************************************************************************************

TASK [configure loop protect timer] **************************************************************************************************************************
fatal: [switch01]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "msg": "show configurationInvalid input: configuration\r\nswitch01#", "rc": -32603}
	to retry, use: --limit @/Users/me/.ansible-retry/examples.retry

PLAY RECAP ***************************************************************************************************************************************************
switch01      : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

This happens because `show configuration` is not a valid option on Aruba 2930F. Instead, show config works. 

Relevant code is [here](https://github.com/ansible-collections/community.network/blob/33ea56c91ba6449a01ffe8cbb6af067fadcec657/plugins/modules/network/aruba/aruba_config.py#L366)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
aruba_config

##### ANSIBLE VERSION
```
ansible 2.10.1
  config file = /Users/me/repos/ansible/conf/ansible-prod.cfg
  configured module search path = ['/Users/me/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/me/Library/Python/3.8/lib/python/site-packages/ansible
  executable location = /Users/me/Library/Python/3.7/bin/ansible
  python version = 3.8.2 (default, Aug 25 2020, 09:23:57) [Clang 12.0.0 (clang-1200.0.32.2)]
```

##### CONFIGURATION
Hosts:
```
all:
  vars:
    ansible_ssh_common_args: "-o PubkeyAuthentication=no"
    ansible_user: admin
    ansible_connection: local
    ansible_network_os: arubaos
    loop_protect_ports: "1-48"
  hosts:
    switch01
```

##### OS / ENVIRONMENT
macOS Catalina
Aruba 2930F / Aruba 2530

##### STEPS TO REPRODUCE
Simply run the code bellow:
```
    - name: configure loop protect timer
      community.network.aruba_config:
        backup: true
        save_when: modified
        lines:
          - loop-protect {{ loop_protect_ports }}
          - loop-protect disable-timer 120
```

##### EXPECTED RESULTS
Config should be saved successfully. 

##### ACTUAL RESULTS
Task fails, config file is not saved.
