### ISSUE TITLE
module netscaler_service has improper example

### ISSUE THREAD

**Issue by djohnson1865** [ansible-collections/community.network#221]
##### SUMMARY

In the module netscaler_service documentation, the only example listed has an improper configuration.
```
# Monitor monitor-1 must have been already setup

- name: Setup http service
  gather_facts: False
  delegate_to: localhost
  netscaler_service:
    nsip: 172.18.0.2
    nitro_user: nsroot
    nitro_pass: nsroot

    state: present

    name: service-http-1
    servicetype: HTTP
    ipaddress: 10.78.0.1
    port: 80

    monitor_bindings:
      - monitor-1
  ```
However, the monitor under monitor_bindings should be a dictionary not a string. I'm not familiar enough to know what the preferred yaml style would be for ansible documentation, but I think the example should be more along the lines of
```
    monitor_bindings:
      - { monitorname: monitor-1 }
```
The existing example will throw an error if used similarly.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

netscaler_service

##### ANSIBLE VERSION
Not applicable, in online documentation, but valid for Ansible 2.9
