### ISSUE TITLE
Add support decode bitmap for ce_switchport module

### ISSUE THREAD

**Issue by efrikin** [ansible-collections/community.network#315]
##### SUMMARY
Currently, ansible module `ce_switchport` return few values as bitmap for trunk and hybrid modes. 
This is not user frendly format for reading and will be better if we can see diff state between `end_state` and `proposed`.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

community.network.ce_switchport

##### ADDITIONAL INFORMATION

```yaml
- hosts: sw
  gather_facts: false
  vars:
    ansible_connection: ansible.netcommon.netconf
    ansible_user: root
    ansible_password: PASSWD
    ce__create_vlan: 3000

  tasks:
    - name: Create vlans to {{ inventory_hostname }}
      community.network.ce_vlan:
        vlan_id: "{{ ce__create_vlan }}"
        state: present

    - name: Test ce_switchport
      community.network.ce_switchport:
        interface: "40GE2/1/1"
        mode: trunk
        trunk_vlans: "{{ ce__create_vlan }}"

```

```bash
$ ansible-playbook -i inventory.yml playbook.yml -vvv

TASK [Create vlans to 10.10.10.10] ********************************************************************************************************************************
ok: [10.10.10.10]

TASK [Test ce_switchport] *******************************************************************************************************************************************
...
ok: [10.10.10.10] => {
    "changed": false,
    "end_state": {
        "interface": "40GE2/1/1",
        "mode": "trunk",
        "switchport": "enable",
        "trunk_pvid": "1",
        "trunk_vlans": "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000C000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    },
    "existing": {
        "interface": "40GE2/1/1",
        "mode": "trunk",
       "switchport": "enable",
        "trunk_pvid": "1",
        "trunk_vlans": "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000C000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    },
    "invocation": {
        "module_args": {
            "default_vlan": null,
            "interface": "40GE2/1/1",
            "mode": "trunk",
            "provider": null,
            "pvid_vlan": null,
            "state": "present",
            "tagged_vlans": null,
            "trunk_vlans": "3000",
            "untagged_vlans": null
        }
    },
    "proposed": {
        "interface": "40GE2/1/1",
        "mode": "trunk",
        "pvid_vlan": null,
        "state": "present",
        "trunk_vlans": "3000"
    },
    "updates": []
}

PLAY RECAP **********************************************************************************************************************************************************
10.10.10.10              : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

```

From log above we can see, that `trunk_vlans` in `existing` and `end_state` in bitmap format
