### ISSUE TITLE
Cumulus Linux: support for new nvue syntax

### ISSUE THREAD

**Issue by MEschenbacher** [ansible-collections/community.network#319]
##### SUMMARY

Cumulus Linux now supports a new command line syntax [nvue](https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-44/System-Configuration/NVIDIA-User-Experience-NVUE/#list-all-nvue-commands). Currently, there are some configurations which can not be done with nclu but only with nvue and vice versa.

Example for nclu lacking configuration options which nvue provides: https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-44/Network-Virtualization/VXLAN-Devices/#single-vxlan-device

Example for nvue lacking configuration options which nclu provides: https://docs.nvidia.com/networking-ethernet-software/cumulus-linux-43/Layer-3/VRFs/Virtual-Routing-and-Forwarding-VRF/

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
I propose either
  - option 1) a new module similar to `community.network.nclu` called `community.network.nvue`
  - option 2) a compatibility mode to `community.network.nclu` which can then be used to issue not only nclu commands but also nvue commands

##### ADDITIONAL INFORMATION

I am leaning towards option 2 because neither nclu nor nvue are currently *completely* covering all possible configuration options and therefore one *single* module should be able to provide an interface all configuration options.

Example for option 2) (note the *new* parameter `cli` which should default to `nvue` but may be set to `nvue`.

```yml
- name: configure vrf
  community.network.nclu:
    cli: nvue
    template: |
      {% for name in ['internal', 'external'] %}
        add vrf {{name}} vrf-table auto
      {% endfor %}
```
