### ISSUE TITLE
Unable to decode JSON from response to exec_command on Nokia SROS

### ISSUE THREAD

**Issue by mkioga** [ansible-collections/community.network#324]
##### SUMMARY

I am trying to run commands on Nokia 7210/7705 Router using examples in this link.
https://docs.ansible.com/ansible/latest/collections/community/network/sros_command_module.html

The commands run fine on Older Ansible server (ansible 2.9.13 and Python 2.7.5) but fail on Newer ansible server (ansible 2.9.25 and Python 3.6.8) with "Unable to decode JSON" Error message.

Please advise how I can get this playbook working again in new ansible 2.9.25 and Python 3.6.8

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.network.sros_command

##### ANSIBLE VERSION

```
[USERNAME@OLD-ANSIBLE]$  ansible --version
ansible 2.9.13
  config file = /home/238434/Nokia7705SNMPv3/ansible.cfg
  configured module search path = [u'/home/238434/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Sep 12 2018, 05:31:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]


[USERNAME@NEW-ANSIBLE]$ ansible --version
ansible 2.9.25
  config file = /home/238434/Nokia7705SNMPv3/ansible.cfg
  configured module search path = ['/home/238434/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Mar 18 2021, 08:58:41) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]

```

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```

======================
Playbook I am using:
======================

# ansible-playbook nokia-testing-connection.yml -i inventory/test-nokia-router.yml -u admin -k

---
- name: Playbook to connect to Nokia 7210 Router
  hosts: all
  gather_facts: False
  connection: network_cli 
  # connection: ansible.netcommon.network_cli # Used this for testing but it failed.

  vars:
    ansible_network_os: "sros"

  tasks:
    - name: run show system information | match "SNMP Engine ID"
      community.network.sros_command:
        commands: show system information | match "SNMP Engine ID"
        # provider: "{{ cli }}" # We don't need this line if using connection network_cli 
      register: engine_ID
    
    - name: print engine id
      ansible.builtin.debug:
        var: engine_ID # This prints the output of engine ID

```

##### EXPECTED RESULTS

These are the results from Older Ansible version 2.9.13 with Python 2.7.5

[USERNAME@OLD-ANSIBLE]$ ansible-playbook nokia-testing-connection.yml -i inventory/test-nokia-router.yml -u admin -k
SSH password: 

PLAY [Playbook to connect to Nokia 7210 Router] **********************************************************************************************************

TASK [run show system information | match "SNMP Engine ID"] **********************************************************************************************
ok: [NOKIA-ROUTER]

TASK [print engine id] ****************************************************************************************
ok: [NOKIA-ROUTER] => {
    "changed": false, 
    "engine_ID": {
        "ansible_facts": {
            "discovered_interpreter_python": "/usr/bin/python"
        }, 
        "changed": false, 
        "failed": false, 
        "stdout": [
            "SNMP Engine ID            : 0099197f00DDDDWWW444555"
        ], 
        "stdout_lines": [
            [
                "SNMP Engine ID            : 0099197f00DDDDWWW444555"
            ]
        ]
    }
}

PLAY RECAP *******************************************************************************************************
NOKIA-ROUTER  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

##### ACTUAL RESULTS

```
These are the error results I am getting using Newer Ansible version 2.9.25 with Python 3.6.8

[USERNAME@NEW-ANSIBLE]$ ansible-playbook nokia-testing-connection.yml -i inventory/test-nokia-router.yml -u admin -k
SSH password: 

PLAY [Playbook to connect to Nokia 7210 Router] **********************************************************************************************************

TASK [run show system information | match "SNMP Engine ID"] **********************************************************************************************
fatal: [NOKIA-ROUTER]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/libexec/platform-python"}, "changed": false, "msg": "Unable to decode JSON from response to exec_command({\"command\": \"show system information | match \\\"SNMP Engine ID\\\"\", \"prompt\": null, \"answer\": null}). Received 'None'.", "rc": 1}

PLAY RECAP ***********************************************************************************************************************************************
NOKIA-ROUTER                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   



```
