### ISSUE TITLE
HUAWEI CE: community.network.ce_link_status is broken

### ISSUE THREAD

**Issue by MVKozlov** [ansible-collections/community.network#461]
##### SUMMARY
Can't get it to work :)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.network.ce_link_status

##### ANSIBLE VERSION
```
ansible [core 2.13.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible', '/etc/ansible/library']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = /etc/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION
```
# /usr/local/lib/python3.8/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.network 4.0.1
```

##### CONFIGURATION
```
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
COLLECTIONS_PATHS(/etc/ansible/ansible.cfg) = ['/etc/ansible/collections']
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 50
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = ['/usr/share/ansible', '/etc/ansible/library']
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
DISPLAY_SKIPPED_HOSTS(/etc/ansible/ansible.cfg) = True
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = /usr/bin/python3
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 60
```

##### OS / ENVIRONMENT
Ubuntu 20.04.4 LTS

##### STEPS TO REPRODUCE
```yaml
---
#variant 1
- hosts: huawei
  connection: local
  gather_facts: no
  vars:
    ansible_network_os: community.network.ce
    cli:
      host: "{{ inventory_hostname }}"
      port: 22
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      transport: cli

  tasks:
    - name: Get all interfaces link status information
      community.network.ce_link_status:
        interface: all
        provider: "{{ cli }}"


#variant 2
- hosts: huawei
  connection: ansible.netcommon.network_cli
  gather_facts: no
  vars:
    ansible_network_os: community.network.ce
  tasks:
    - name: Get all interfaces link status information
      community.network.ce_link_status:
        interface: all
```

##### EXPECTED RESULTS
successfull connection

##### ACTUAL RESULTS
```paste below
#variant 1
 msg: connection local support for this module has been removed use either 'network_cli' or 'ansible.netcommon.network_cli' connection


#variant 2
 msg: Connection type 'ansible.netcommon.network_cli' is not valid for 'community.network.ce_link_status' module.
```

at the same time module **community.network.ce_command** works with `connection: ansible.netcommon.network_cli`
