### ISSUE TITLE
Connection local isn't supported for SROS

### ISSUE THREAD

**Issue by indirakas** [ansible-collections/community.network#510]
##### SUMMARY

We upgraded ansible to the latest version 2.12, which broke sros_command module in the task with the following error:
"connection local support for this module has been removed use either 'network_cli' or 'ansible.netcommon.network_cli' connection"
However, when I tried switching to the connection: network_cli, which also involved setting ansible_network_os, I realized that `sros` isn't supported, based on this: https://docs.ansible.com/ansible/latest/network/user_guide/platform_index.html#settings-by-platform
So which connection should I use for SROS?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.network.sros_command

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.9]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.13 (default, Jun 14 2022, 17:49:07) [GCC 8.5.0 20210514 (Red Hat 8.5.0-13)]
  jinja version = 2.11.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
collections:
  - community.general
  - community.network
  - ansible.netcommon
  - ansible.utils
  - ansible.netcommon
  - ansible.network
  - ansible.posix
  - ansible.security
  - ansible.utils
  - ansible.windows
  - ansible.yang
  - servicenow.servicenow
  - nokia.sros

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```
playbook:
- name: Get-config-nokia
  hosts: nokia
  connection: local
  gather_facts: no
  roles:
    - get-config-nokia
  
task in a role:
    - name: Collect show debug
      community.network.sros_command:
        command: show debug
      register: show_debug
vars:
ansible_user: "ansible_networking"

```

##### EXPECTED RESULTS

it was supposed to pull `show debug` output

##### ACTUAL RESULTS

```
TASK [get-config-nokia : Collect show debug] ***********************************
task path: /runner/project/roles/get-config-nokia/tasks/main.yml:6
fatal: [***]: FAILED! => {
    "changed": false,
    "msg": "connection local support for this module has been removed use either 'network_cli' or 'ansible.netcommon.network_cli' connection"
}

```
