### ISSUE TITLE
Feature: Support for startup config in exos_config & exos_facts

### ISSUE THREAD

**Issue by ng-bsy** [ansible-collections/community.network#512]
##### SUMMARY

To my understanding, `exos_config` and `exos_facts` only represent and let you manipulate or make backups of the _current active (running) config_.
For my use case I'd like to see the same possibilities for the _saved (startup) config_.
E.g.
- Make a backup of the _current startup config_ via `exos_config`
- Get _current startup config_ via `exos_facts`

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

- exos_config
- exos_facts

##### ADDITIONAL INFORMATION

```yaml
# use of exos_facts
- community.network.exos_facts:
    gather_subset: config
  register: exos_facts
- ansible.builtin.debug:
    msg:
      - "{{ exos_facts.ansible_facts.ansible_net_config_startup }}"
      - "{{ exos_facts.ansible_facts.ansible_net_config_active }}"

# use of exos_config
- community.network.exos_config:
    backup: yes
    backup_options:
      filename: backup_startup.cfg
      dir_path: /home/user
    config: startup
      
```

Thanks a lot

**Comment by Andersson007** [comment]
@ng-bsy hello, thanks for reporting the issue!

cc (team_extreme) @LindsayHill @ujwalkomarla

in case someone new wants to pick it up, there's the [Quick start dev guide](https://docs.ansible.com/ansible/devel/community/create_pr_quick_start.html)

**Comment by Andersson007** [comment]
@ng-bsy the task you posted looks like it has a simple interface, hasn't it?
Maybe rather than writing a new piece of code someone needs to maintain, would it be good just to put info about your solutions in related modules, e.g. in DOCUMENTATION and EXAMPLES sections?
Something like:
```
- name: Backup the startup config
  ansible.netcommon.net_get:
    src: nms.xsf
    dest: /home/user/startup_config
```
what do you think? If you're OK with it, would you like to do it using the [Quick-start guide](https://docs.ansible.com/ansible/devel/community/create_pr_quick_start.html)?
