### ISSUE TITLE
Netscaler_nitro_request should de url-/percent-encoding in the module instead of expecting already-encoded params

### ISSUE THREAD

**Issue by JonasVerhofste** [ansible-collections/community.network#53]
##### SUMMARY
As discussed in #52 , the module currently expects parameters to be url-/percent-encoded  in the play (either hardcoded or through jinja-templating), whilst it would make more sense to do this in the module itself (making them easier to read and write).

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
netscaler_nitro_request

##### ADDITIONAL INFORMATION
Because of the weirdness that is the netscaler API, some parameters need to be url-encoded, whilst others don't. Currently, this is left up to the user: the code only builds the correct query, but doesn't do any parsing of the parameter-strings themselves. This makes for pretty confusing plays, where you have parameters that need `{{ myvar | urlencode | replace('/', '%2F') }}` and others don't.

It would make more sense to decide and do this in the code, making writing tasks a lot easier (as you don't need to go verify if this particular param needs encoding or not).

However, since changing this would be a backwards incompatible change, we'll have to feature flag this option, as [kindly and correctly suggested](https://github.com/ansible-collections/community.network/pull/52#issuecomment-640238767) by @felixfontein.

Example of how current tasks look:
```yaml
- name: Do some filter
  netscaler_nitro_request:
    nsip: mynetscaler.mydomain.mytld
    nitro_user: myuser
    nitro_pass: mypass
    nitro_protocol: https
    operation: get_filtered
    resource: sslcertkey
    filter:
      certificatetype: "{{ '/ROOT_CERT|INTM_CERT/' | urlencode | replace('/', '%2F') }}"
      subject: "{{ '/COMODO/' | replace('/', '%2F') }}"
```

Example of how this would look with the feature flag:
```yaml
- name: Do some filter
  netscaler_nitro_request:
    nsip: mynetscaler.mydomain.mytld
    nitro_user: myuser
    nitro_pass: mypass
    nitro_protocol: https
    operation: get_filtered
    resource: sslcertkey
    percent-encode: yes
    filter:
      certificatetype: /ROOT_CERT|INTM_CERT/
      subject: /COMODO/
```
