### ISSUE TITLE
Issues with aruba_command module when running against Mobility Conductor

### ISSUE THREAD

**Issue by rtorres-github** [ansible-collections/community.network#553]
##### SUMMARY

Issues with aruba_command module when running against Mobility Conductor. I can run the CLI commands against a Managed Device (Aruba Gateways) running version 8.10.0.6 but unable to do so on the Mobility Conductor. I get the following error "Unable to decode JSON from response to exec_command({\"command\": \"show version\", \"prompt\": null, \"answer\": null}). Received 'None'."

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

module: aruba_command
ansible_connection: "network_cli"
ansible_network_os: "aruba"

Overwrite the applied role in the task with the networkcli and aruba ansible connection and network os listed above

##### ADDITIONAL INFORMATION

Task is to run show commands against the Mobility Conductor and Managed Devices

```yaml
- name: aruba controller browse
  hosts: "{{ device_name }}"
  roles:
    - role: arubanetworks.aos_wlan_role
  gather_facts: no
  vars:
    device_name: ""
    command_list: ""

  tasks:

    - name: show commands
      aos_show_command:
        command: "{{ item }}"
      loop: "{{ command_list }}"
      register: command_output


    - name: filter output
      set_fact:
        output: "{{ command_output | ansible.utils.remove_keys(target=['_meta']) | json_query(query_pattern) }}"
      vars:
        query_pattern: 'results[].{command: item, results: msg.*[]}'


    - name: format output
      set_fact:
        structured_output: "{{ structured_output | default([]) + [{'command': item['command'], 'results': item['results'] | map('split','\n') | flatten if item['results'] | select('contains', '\n') else item['results']}] }}"
      loop: "{{ output }}"


    - name: print output
      debug:
        msg: "{{ structured_output }}"


```

##### COMMANDS TO TEST

show ap active
show ap database
show ap database-summary
show clock
show cpuload
show debug
show image version
show ip interface brief
show ip route
show logging level verbose
show memory
show configuration received
show storage
show switch ip
show version
show vlan
show lc-cluster group-membership
show switches
